from typing import Optional, Protocol, runtime_checkable
from app.modules.competitions.schemas.competition_schemas import (
    CreateCompetitionInput,
    CompetitionDTO,
    CategoryInfoDTO,
)
from app.modules.competitions.schemas.team_schemas import (
    RegisterTeamInput,
    PayCompetitionFeeInput,
    TeamDTO,
    StudentCompetitionDTO,
    TeamRegistrationResultWithWarningDTO,
    AddTeamMemberInput,
    AddTeamMemberResultWithWarningDTO,
    TeamMemberDTO,
    TeamMemberRosterDTO,
    PayCompetitionFeeResponseDTO,
    TeamWithMembersDTO,
    CompetitionSummaryDTO,
)


@runtime_checkable
class CompetitionServiceInterface(Protocol):
    def create_competition(self, cmd: CreateCompetitionInput) -> CompetitionDTO: ...
    def list_competitions(self) -> list[CompetitionDTO]: ...
    def get_competition_by_id(self, competition_id: int) -> CompetitionDTO | None: ...
    def update_competition(self, competition_id: int, **kwargs) -> CompetitionDTO | None: ...
    def delete_competition(self, competition_id: int) -> bool: ...
    def list_categories(self, competition_id: int) -> list[CategoryInfoDTO]: ...
    def get_competition_summary(self, competition_id: int) -> CompetitionSummaryDTO | None: ...


@runtime_checkable
class TeamServiceInterface(Protocol):
    def get_student_competitions(self, student_id: int) -> list[StudentCompetitionDTO]: ...
    def register_team(self, cmd: RegisterTeamInput, current_user_id: Optional[int] = None) -> TeamRegistrationResultWithWarningDTO: ...
    def get_team_by_id(self, team_id: int) -> TeamDTO | None: ...
    def get_team_for_user(self, team_id: int, current_user) -> TeamDTO | None: ...
    def list_teams(self, competition_id: int, category: Optional[str] = None, subcategory: Optional[str] = None) -> list[TeamDTO]: ...
    def list_teams_for_coach(self, competition_id: int, coach_id: int, category: Optional[str] = None, subcategory: Optional[str] = None) -> list[TeamDTO]: ...
    def list_teams_for_user(self, competition_id: int, current_user, category: Optional[str] = None, subcategory: Optional[str] = None) -> list[TeamDTO]: ...
    def get_teams_with_members_for_user(self, competition_id: int, current_user, category: Optional[str] = None, subcategory: Optional[str] = None) -> list[TeamWithMembersDTO]: ...
    def get_team_members_for_team(self, team_id: int) -> list[TeamMemberDTO]: ...
    def get_teams_with_members(self, competition_id: int, category: Optional[str] = None, subcategory: Optional[str] = None) -> list[TeamWithMembersDTO]: ...
    def update_team(self, team_id: int, **kwargs) -> TeamDTO | None: ...
    def delete_team(self, team_id: int) -> bool: ...
    def update_placement(self, team_id: int, placement_rank: int, placement_label: Optional[str] = None, current_user_id: Optional[int] = None) -> TeamDTO: ...
    def add_team_member_to_existing(self, team_id: int, student_id: int, amount_due: float = 0.0, current_user_id: Optional[int] = None) -> AddTeamMemberResultWithWarningDTO: ...
    def get_team_member(self, team_id: int, student_id: int) -> TeamMemberDTO | None: ...
    def remove_team_member(self, team_id: int, student_id: int) -> bool: ...
    def list_team_members(self, team_id: int) -> list[TeamMemberRosterDTO]: ...
    def pay_competition_fee(self, cmd: PayCompetitionFeeInput) -> PayCompetitionFeeResponseDTO: ...
    def refund_competition_fee(self, team_member_id: int, amount: float, current_user_id: Optional[int] = None) -> "RefundResultDTO": ...
