"""
app/modules/academics/group/level/interface.py
────────────────────────────────────────
Interfaces for the Group Level slice.
"""
from typing import Protocol, runtime_checkable
from typing import Optional
from app.modules.academics.models.group_level_models import GroupLevel
from app.modules.academics.group.level.schemas import GroupLevelReadDTO, GroupLevelDetailDTO


@runtime_checkable
class GroupLevelServiceInterface(Protocol):
    """Contract for Group Level business logic."""
    def get_level_by_number(self, group_id: int, level_number: int) -> GroupLevelDetailDTO: ...
    def get_paginated_levels(self, group_id: int, status: Optional[str] = None, include_inactive: bool = False, skip: int = 0, limit: int = 50) -> tuple[list[GroupLevelReadDTO], int]: ...
    def get_level_history(self, group_id: int) -> list[GroupLevel]: ...
    def update_level_instructor(self, group_id: int, level_number: int, instructor_id: int) -> GroupLevel: ...
    def cancel_level(self, group_id: int, level_number: int) -> GroupLevel: ...


@runtime_checkable
class GroupLevelRepositoryInterface(Protocol):
    """Contract for Group Level database access."""
    def get_group_level_by_number(self, session, group_id: int, level_number: int) -> GroupLevel | None: ...
    def get_current_group_level(self, session, group_id: int) -> GroupLevel | None: ...
    def get_levels_by_group(self, session, group_id: int, status: Optional[str] = None, include_inactive: bool = False, skip: int = 0, limit: int = 50) -> tuple[list[GroupLevel], int]: ...
    def list_group_levels(self, session, group_id: int, include_inactive: bool = False) -> list[GroupLevel]: ...
    def update_group_level(self, session, level: GroupLevel) -> GroupLevel: ...
    def cancel_group_level(self, session, group_id: int, level_number: int) -> GroupLevel | None: ...
    def complete_group_level(self, session, group_id: int, level_number: int) -> GroupLevel | None: ...
