"""
app/modules/academics/group/directory/interface.py
────────────────────────────────────────
Interfaces for the Group Directory slice.
"""
from typing import Protocol, runtime_checkable
from app.modules.academics.models.course_models import Group
from app.modules.academics.group.core.schemas import EnrichedGroupDTO
from app.modules.academics.group.directory.schemas import GroupedGroupsResult


@runtime_checkable
class GroupDirectoryServiceInterface(Protocol):
    """Contract for Group Directory business logic."""
    def get_all_active_groups(self, include_inactive: bool = False) -> list[Group]: ...
    def get_all_active_groups_enriched(self) -> list[EnrichedGroupDTO]: ...
    def get_todays_groups_enriched(self) -> list[EnrichedGroupDTO]: ...
    def get_enriched_group_by_id(self, group_id: int) -> EnrichedGroupDTO | None: ...
    def search_groups(self, query: str, status: str | None = None, skip: int = 0, limit: int = 20) -> tuple[list[Group], int]: ...
    def get_groups_by_type(self, group_type: str, status: str | None = None, skip: int = 0, limit: int = 50) -> tuple[list[Group], int]: ...
    def get_all_archived_groups(self, include_inactive: bool = False) -> list[Group]: ...
    def get_groups_by_course(self, course_id: int, include_inactive: bool = False, level_number: int | None = None, skip: int = 0, limit: int = 50) -> tuple[list[Group], int]: ...
    def get_groups_grouped(self, group_by: str, skip: int = 0, limit: int = 50, search: str | None = None) -> GroupedGroupsResult: ...


@runtime_checkable
class GroupDirectoryRepositoryInterface(Protocol):
    """Contract for Group Directory database access."""
    def list_all_active_groups(self, session, include_inactive: bool = False) -> list[Group]: ...
    def get_enriched_groups(self, session) -> list[EnrichedGroupDTO]: ...
    def get_enriched_groups_by_date(self, session, target_date: str) -> list[EnrichedGroupDTO]: ...
    def get_enriched_group_by_id(self, session, group_id: int) -> EnrichedGroupDTO | None: ...
    def search_groups(self, session, query: str, status: str | None = None, skip: int = 0, limit: int = 20) -> tuple[list[Group], int]: ...
    def get_groups_by_type(self, session, group_type: str, status: str | None = None, skip: int = 0, limit: int = 50) -> tuple[list[Group], int]: ...
    def get_all_archived_groups(self, session, include_inactive: bool = False) -> list[Group]: ...
    def get_groups_by_course(self, session, course_id: int, include_inactive: bool = False, level_number: int | None = None, skip: int = 0, limit: int = 50) -> tuple[list[Group], int]: ...
