from dataclasses import dataclass
from typing import Protocol, Optional, runtime_checkable, Any
from datetime import date

from app.modules.crm.models.student_models import Student, StudentStatus
from app.modules.crm.models.parent_models import Parent
from app.modules.crm.schemas.student_schemas import RegisterStudentCommandDTO, UpdateStudentDTO, StudentStatusSummaryDTO

@dataclass(frozen=True)
class StudentSummaryDTO:
    """Immutable summary row — used internally between services."""
    id: int
    full_name: str
    phone: Optional[str]
    gender: Optional[str]
    status: str
    is_active: bool
    current_group_id: Optional[int]
    current_group_name: Optional[str]
    date_of_birth: Optional[date]

@dataclass(frozen=True)
class StudentGroupedResultDTO:
    """Result of a grouping operation."""
    group_by: str
    total_unique_students: int
    groups: list  # list[StudentGroupBucketDTO]

@dataclass(frozen=True)
class StudentGroupBucketDTO:
    key: str
    label: str
    count: int
    students: list  # list[StudentSummaryDTO]

@dataclass(frozen=True)
class StudentBalanceSummaryDTO:
    total_due: float
    total_discounts: float
    total_paid: float
    net_balance: float
    enrollment_count: int
    unpaid_enrollments: int

@dataclass(frozen=True)
class AttendanceStatsDTO:
    total_sessions: int
    attended: int
    absent: int
    cancelled: int
    attendance_rate: float

@runtime_checkable
class IStudentRepository(Protocol):
    def create(self, student: Student) -> Student: ...
    def get_by_id(self, student_id: int) -> Optional[Student]: ...
    def get_all(self, skip: int, limit: int) -> list[Student]: ...
    def get_all_enriched(self, include_inactive: bool) -> list[StudentSummaryDTO]: ...
    def search(self, query: str) -> list[Student]: ...
    def count(self, active_only: bool) -> int: ...
    def count_by_status(self, status: StudentStatus) -> int: ...
    def update_status(self, student_id: int, new_status: StudentStatus,
                      user_id: Optional[int], notes: Optional[str]) -> Optional[Student]: ...
    def set_waiting_priority(self, student_id: int, priority: int) -> Optional[Student]: ...
    def delete(self, student_id: int) -> bool: ...
    def get_with_parent(self, student_id: int) -> Optional[tuple]: ...
    def get_student_balance_summary(self, student_id: int) -> StudentBalanceSummaryDTO: ...
    def get_student_siblings_with_details(self, student_id: int) -> list: ...
    def get_attendance_stats(self, student_id: int) -> AttendanceStatsDTO: ...

@runtime_checkable
class IParentRepository(Protocol):
    def create(self, parent: Parent) -> Parent: ...
    def get_by_id(self, parent_id: int) -> Optional[Parent]: ...
    def get_by_phone(self, phone: str) -> Optional[Parent]: ...
    def get_all(self, skip: int, limit: int) -> list[Parent]: ...
    def search(self, query: str) -> list[Parent]: ...
    def count(self) -> int: ...
    def update(self, parent_id: int, data: dict) -> Optional[Parent]: ...
    def delete(self, parent_id: int) -> Optional[Parent]: ...

@runtime_checkable
class IStudentService(Protocol):
    """CRUD + status operations on a single student record."""
    def register(self, command: RegisterStudentCommandDTO) -> tuple[Student, list]: ...
    def get_by_id(self, student_id: int) -> Optional[Student]: ...
    def update(self, student_id: int, data: UpdateStudentDTO) -> Student: ...
    def update_status(self, student_id: int, new_status: StudentStatus,
                      user_id: Optional[int], notes: Optional[str]) -> Student: ...
    def toggle_status(self, student_id: int, user_id: Optional[int],
                      notes: Optional[str]) -> Student: ...
    def set_waiting_priority(self, student_id: int, priority: int,
                             user_id: Optional[int]) -> Student: ...
    def delete(self, student_id: int) -> bool: ...

@runtime_checkable
class ISearchService(Protocol):
    """Search and listing operations."""
    def search(self, query: str) -> list[Student]: ...
    def list_all(self, skip: int, limit: int) -> list: ...
    def count(self, active_only: bool) -> int: ...
    def get_by_status(self, status: StudentStatus, skip: int, limit: int) -> list[Student]: ...
    def get_waiting_list(self, skip: int, limit: int, ordered: bool) -> list[Student]: ...
    def get_status_summary(self) -> StudentStatusSummaryDTO: ...

@runtime_checkable
class IGroupingService(Protocol):
    """Group students by a specified dimension."""
    def get_grouped(self, group_by: str, include_inactive: bool) -> StudentGroupedResultDTO: ...

@runtime_checkable
class IReportingService(Protocol):
    """Cross-domain summary and history reporting."""
    def get_student_details(self, student_id: int) -> Any: ...  # Returns StudentWithDetails
    def get_balance_summary(self, student_id: int) -> StudentBalanceSummaryDTO: ...
    def get_attendance_stats(self, student_id: int) -> AttendanceStatsDTO: ...
    def get_siblings(self, student_id: int) -> list: ...
