"""
app/modules/academics/course/interface.py
────────────────────────────────────────
Interfaces for the Course slice.
"""
from typing import Protocol, runtime_checkable, Sequence
from app.modules.academics.models.course_models import Course
from app.modules.academics.course.schemas import AddNewCourseInput, UpdateCourseDTO, CourseStatsDTO


@runtime_checkable
class CourseServiceInterface(Protocol):
    """Contract for Course business logic."""
    def list_active_courses(self) -> Sequence[Course]: ...
    def get_course_by_id(self, course_id: int) -> Course | None: ...
    def get_course_by_name(self, name: str) -> Course | None: ...
    def add_new_course(self, data: AddNewCourseInput) -> Course: ...
    def update_course(self, course_id: int, data: UpdateCourseDTO) -> Course: ...
    def get_all_course_stats(self) -> list[CourseStatsDTO]: ...
    def get_course_stats(self, course_id: int) -> CourseStatsDTO | None: ...


@runtime_checkable
class CourseRepositoryInterface(Protocol):
    """Contract for Course database access."""
    def get_course_by_id(self, session, course_id: int) -> Course | None: ...
    def get_course_by_name(self, session, name: str) -> Course | None: ...
    def list_active_courses(self, session) -> Sequence[Course]: ...
    def create_course(self, session, course: Course) -> Course: ...
    def update_course_price(self, session, course_id: int, new_price: float) -> Course | None: ...
    def get_all_course_stats(self, session) -> list[CourseStatsDTO]: ...
    def get_course_stats(self, session, course_id: int) -> CourseStatsDTO | None: ...
