-- =============================================================================
-- FINANCE TABLES
-- Receipts, payments, and financial transactions
-- Dependencies: students (03_tables_crm.sql), enrollments (05_tables_enrollments.sql),
--               users (02_tables_core.sql)
-- =============================================================================

DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS receipts CASCADE;
DROP TABLE IF EXISTS receipt_templates CASCADE;

-- =============================================================================
-- RECEIPT_TEMPLATES
-- Configurable receipt templates
-- =============================================================================
CREATE TABLE receipt_templates (
    id SERIAL PRIMARY KEY,
    template_name TEXT NOT NULL UNIQUE,
    template_content TEXT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    is_default BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE receipt_templates IS 'Configurable receipt templates for receipt generation';
COMMENT ON COLUMN receipt_templates.template_content IS 'Template text with placeholders';
COMMENT ON COLUMN receipt_templates.is_default IS 'True if this is the default template';

-- =============================================================================
-- RECEIPTS
-- Receipt header records
-- =============================================================================
CREATE TABLE receipts (
    id SERIAL PRIMARY KEY,
    payer_name TEXT,
    payment_method TEXT CHECK (
        payment_method IN ('cash', 'card', 'transfer', 'online')
    ),
    received_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    receipt_number TEXT UNIQUE,
    receipt_template TEXT,
    notes TEXT,
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    auto_generated BOOLEAN DEFAULT FALSE,
    sent_to_parent BOOLEAN DEFAULT FALSE,
    sent_at TIMESTAMPTZ
);

COMMENT ON TABLE receipts IS 'Receipt header records for payments';
COMMENT ON COLUMN receipts.receipt_number IS 'Unique receipt identifier/number';
COMMENT ON COLUMN receipts.receipt_template IS 'Name of template used for this receipt';
COMMENT ON COLUMN receipts.auto_generated IS 'True if receipt was auto-generated by system';
COMMENT ON COLUMN receipts.sent_to_parent IS 'True if receipt has been sent to parent';
COMMENT ON COLUMN receipts.sent_at IS 'Timestamp when receipt was sent';

-- =============================================================================
-- PAYMENTS
-- Financial transactions (charges, payments, refunds)
-- =============================================================================
CREATE TABLE payments (
    id SERIAL PRIMARY KEY,
    receipt_id INTEGER NOT NULL REFERENCES receipts(id) ON DELETE RESTRICT,
    student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE RESTRICT,
    enrollment_id INTEGER REFERENCES enrollments(id) ON DELETE SET NULL,
    amount DECIMAL(10, 2) NOT NULL CHECK (amount != 0),
    transaction_type TEXT NOT NULL CHECK (
        transaction_type IN ('charge', 'payment', 'refund')
    ),
    payment_type TEXT CHECK (
        payment_type IN ('course_level', 'competition', 'other')
    ),
    discount_amount DECIMAL(10, 2) DEFAULT 0 CHECK (discount_amount >= 0),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    metadata JSONB DEFAULT '{}',
    deleted_at TIMESTAMPTZ,
    deleted_by INTEGER REFERENCES users(id) ON DELETE SET NULL
);

COMMENT ON TABLE payments IS 'Financial transactions: charges, payments, and refunds';
COMMENT ON COLUMN payments.amount IS 'Transaction amount (positive for charges/payments, negative for refunds)';
COMMENT ON COLUMN payments.transaction_type IS 'Type: charge (debit), payment (credit), or refund';
COMMENT ON COLUMN payments.payment_type IS 'Category: course_level, competition, or other';
COMMENT ON COLUMN payments.discount_amount IS 'Discount applied to this payment';
COMMENT ON COLUMN payments.deleted_at IS 'Soft delete timestamp for voided transactions';

COMMENT ON TABLE payments IS 
'Source of truth for all financial transactions (charge, payment, refund). '
'Enrollment balance is computed in real-time via v_enrollment_balance view. '
'Legacy payment_allocations table deprecated in migration 028 and removed in migration 043.';
