"""Task Interfaces

Protocol contracts for Task repository and service layers.
Allows runtime checkability for mocking/testing.
"""
import uuid
from typing import Optional, Protocol, runtime_checkable

from app.modules.tasks.models import Task, TaskSubtask, TaskComment, TaskTimeLog, TaskStatus, TaskPriority
from app.modules.tasks.schemas import (
    CreateTaskInput,
    UpdateTaskInput,
    CreateTaskSubtaskInput,
    UpdateTaskSubtaskInput,
    CreateTaskCommentInput,
    CreateTaskTimeLogInput,
    TaskReadDTO,
    TaskDetailDTO,
)
from app.modules.auth.models.auth_models import User


@runtime_checkable
class TaskRepositoryInterface(Protocol):
    """Protocol for task repository operations."""

    def create_task(self, dto: CreateTaskInput, assigned_by_user_id: int) -> Task: ...
    def update_task(self, task_id: uuid.UUID, dto: UpdateTaskInput, deleted_by_user_id: Optional[int] = None) -> Optional[Task]: ...
    def get_task_by_id(self, task_id: uuid.UUID) -> Optional[Task]: ...
    def get_task_dto(self, task_id: uuid.UUID) -> Optional[TaskDetailDTO]: ...
    def list_tasks(
        self,
        status: Optional[TaskStatus] = None,
        priority: Optional[TaskPriority] = None,
        assigned_to: Optional[int] = None,
        is_recurring: Optional[bool] = None,
        include_deleted: bool = False,
    ) -> list[TaskReadDTO]: ...
    def soft_delete(self, task_id: uuid.UUID, deleted_by_user_id: int) -> bool: ...

    # Subtasks
    def create_subtask(self, task_id: uuid.UUID, dto: CreateTaskSubtaskInput) -> TaskSubtask: ...
    def update_subtask(self, subtask_id: uuid.UUID, dto: UpdateTaskSubtaskInput) -> Optional[TaskSubtask]: ...
    def get_subtask_by_id(self, subtask_id: uuid.UUID) -> Optional[TaskSubtask]: ...
    def delete_subtask(self, subtask_id: uuid.UUID) -> bool: ...

    # Comments
    def create_comment(self, task_id: uuid.UUID, author_id: int, dto: CreateTaskCommentInput) -> TaskComment: ...
    def get_comment_by_id(self, comment_id: uuid.UUID) -> Optional[TaskComment]: ...
    def delete_comment(self, comment_id: uuid.UUID) -> bool: ...

    # Time logs
    def create_time_log(self, task_id: uuid.UUID, employee_id: int, dto: CreateTaskTimeLogInput) -> TaskTimeLog: ...
    def get_time_log_by_id(self, log_id: uuid.UUID) -> Optional[TaskTimeLog]: ...


@runtime_checkable
class TaskServiceInterface(Protocol):
    """Protocol for task service operations."""

    def create_task(self, dto: CreateTaskInput, current_user: User) -> TaskDetailDTO: ...
    def update_task(self, task_id: uuid.UUID, dto: UpdateTaskInput, current_user: User) -> TaskDetailDTO: ...
    def get_task(self, task_id: uuid.UUID, current_user: User) -> TaskDetailDTO: ...
    def list_tasks(
        self,
        current_user: User,
        status: Optional[TaskStatus] = None,
        priority: Optional[TaskPriority] = None,
        assigned_to: Optional[int] = None,
        is_recurring: Optional[bool] = None,
    ) -> list[TaskReadDTO]: ...
    def soft_delete(self, task_id: uuid.UUID, current_user: User) -> None: ...

    # Subtasks
    def add_subtask(self, task_id: uuid.UUID, dto: CreateTaskSubtaskInput, current_user: User) -> TaskSubtask: ...
    def update_subtask(self, subtask_id: uuid.UUID, dto: UpdateTaskSubtaskInput, current_user: User) -> TaskSubtask: ...
    def delete_subtask(self, subtask_id: uuid.UUID, current_user: User) -> None: ...

    # Comments
    def add_comment(self, task_id: uuid.UUID, dto: CreateTaskCommentInput, current_user: User) -> TaskComment: ...
    def delete_comment(self, comment_id: uuid.UUID, current_user: User) -> None: ...

    # Time logs
    def add_time_log(self, task_id: uuid.UUID, dto: CreateTaskTimeLogInput, current_user: User) -> TaskTimeLog: ...
