"""
app/modules/academics/session/interface.py
────────────────────────────────────────
Interfaces for the Session slice.
"""
from typing import Protocol, runtime_checkable
from datetime import date
from app.modules.academics.models.course_models import CourseSession
from app.modules.academics.session.schemas import AddExtraSessionInput, UpdateSessionDTO

@runtime_checkable
class SessionServiceInterface(Protocol):
    """Contract for Session business logic."""
    def get_session_by_id(self, session_id: int) -> CourseSession | None: ...
    def get_sessions_by_group(self, group_id: int, include_cancelled: bool = False) -> list[CourseSession]: ...
    def add_extra_session(self, data: AddExtraSessionInput) -> CourseSession: ...
    def update_session(self, session_id: int, data: UpdateSessionDTO) -> CourseSession: ...
    def cancel_session(self, session_id: int) -> CourseSession: ...

@runtime_checkable
class SessionRepositoryInterface(Protocol):
    """Contract for Session database access."""
    def get_session_by_id(self, session, session_id: int) -> CourseSession | None: ...
    def list_sessions_by_group(self, session, group_id: int, include_cancelled: bool = False) -> list[CourseSession]: ...
    def list_sessions_by_level(self, session, group_id: int, level_number: int) -> list[CourseSession]: ...
    def count_sessions(self, session, group_id: int, level_number: int) -> int: ...
    def create_session(self, session, course_session: CourseSession) -> CourseSession: ...
    def get_next_session_number(self, session, group_id: int, level_number: int) -> int: ...
    def get_todays_sessions(self, session, specific_date: date | None = None) -> list[CourseSession]: ...
    def delete_session(self, session, session_id: int) -> bool: ...
