"""
app/modules/academics/group/competition/interface.py
────────────────────────────────────────
Interfaces for the Group Competition slice.
"""
from typing import Protocol, runtime_checkable
from app.modules.academics.group.competition.schemas import TeamReadDTO
from app.modules.academics.models.group_level_models import GroupCompetitionParticipation

@runtime_checkable
class GroupCompetitionServiceInterface(Protocol):
    """Contract for Group Competition business logic."""
    def get_teams_by_group(self, group_id: int, include_inactive: bool = False, skip: int = 0, limit: int = 50) -> tuple[list[TeamReadDTO], int]: ...
    def register_team(self, group_id: int, team_id: int, competition_id: int, notes: str | None = None) -> GroupCompetitionParticipation: ...
    def get_group_competitions(self, group_id: int, is_active: bool | None = True) -> list[dict]: ...
    def complete_participation(self, participation_id: int, final_placement: int | None = None) -> GroupCompetitionParticipation: ...
    def update_participation_notes(self, participation_id: int, notes: str) -> GroupCompetitionParticipation: ...
    def withdraw_from_competition(self, participation_id: int, reason: str | None = None) -> dict: ...
    def link_existing_team(self, group_id: int, team_id: int) -> dict: ...
