"""
Email reporter for test results.
Sends failure details to a specified recipient after each module runs.
Uses Gmail SMTP (same credentials as the app's notification system).
"""
import os
import smtplib
import json
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import Optional


class TestEmailReporter:
    """
    Sends structured test failure reports via email.
    
    Usage:
        reporter = TestEmailReporter()
        reporter.send_module_report(
            module_name="Enrollments",
            total=32,
            passed=28,
            failed=4,
            failures=[
                {"test": "test_enroll_student_not_found", "error": "404 != 200", "file": "test_enrollments_full.py:42"},
            ],
            environment="local",
        )
    """
    
    def __init__(
        self,
        sender: Optional[str] = None,
        app_password: Optional[str] = None,
        recipient: str = "ibrahim.ahmd.net@gmail.com",
    ):
        self.sender = sender or os.getenv("GMAIL_SENDER_ADDRESS", "")
        self.app_password = app_password or os.getenv("GMAIL_APP_PASSWORD", "")
        self.recipient = recipient
        self._all_failures: list[dict] = []  # Accumulate across modules
    
    def _build_html_table(self, failures: list[dict]) -> str:
        """Build an HTML table of failures."""
        if not failures:
            return "<p>✅ All tests passed!</p>"
        
        rows = ""
        for f in failures:
            rows += f"""<tr>
                <td style="border:1px solid #ddd;padding:8px">{f.get('test','')}</td>
                <td style="border:1px solid #ddd;padding:8px;color:red">{f.get('error','')}</td>
                <td style="border:1px solid #ddd;padding:8px;font-family:monospace;font-size:12px">{f.get('file','')}</td>
            </tr>"""
        
        return f"""<table style="border-collapse:collapse;width:100%">
            <thead><tr style="background:#f44336;color:white">
                <th style="border:1px solid #ddd;padding:8px">Test</th>
                <th style="border:1px solid #ddd;padding:8px">Error</th>
                <th style="border:1px solid #ddd;padding:8px">File:Line</th>
            </tr></thead>
            <tbody>{rows}</tbody>
        </table>"""
    
    def send_module_report(
        self,
        module_name: str,
        total: int,
        passed: int,
        failed: int,
        failures: list[dict],
        environment: str = "local",
        duration_seconds: float = 0.0,
    ) -> bool:
        """
        Send an email report for a single module's test results.
        
        Args:
            module_name: Name of the module (e.g., "Enrollments")
            total: Total test count
            passed: Passed test count
            failed: Failed test count
            failures: List of dicts with keys: test, error, file
            environment: Test environment name
            duration_seconds: How long the tests took
            
        Returns:
            True if sent successfully, False otherwise
        """
        self._all_failures.extend(failures)
        
        pass_rate = round((passed / total * 100) if total > 0 else 0, 1)
        
        html = f"""<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; }}
        .header {{ background: {"#4CAF50" if failed == 0 else "#f44336"}; color: white; padding: 20px; border-radius: 5px; }}
        .summary {{ margin: 20px 0; }}
        .summary td {{ padding: 8px; }}
    </style>
</head>
<body>
    <div class="header">
        <h2>📊 Test Report: {module_name}</h2>
        <p>Environment: {environment} | {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC</p>
    </div>
    
    <div class="summary">
        <h3>Summary</h3>
        <table>
            <tr><td><strong>Total:</strong></td><td>{total}</td></tr>
            <tr><td><strong>Passed:</strong></td><td>{passed}</td></tr>
            <tr><td><strong>Failed:</strong></td><td style="color:{"green" if failed==0 else "red"}">{failed}</td></tr>
            <tr><td><strong>Pass Rate:</strong></td><td>{pass_rate}%</td></tr>
            <tr><td><strong>Duration:</strong></td><td>{duration_seconds:.1f}s</td></tr>
        </table>
    </div>
    
    <h3>Failure Details</h3>
    {self._build_html_table(failures)}
    
    <hr style="margin-top:30px">
    <p style="color:#666;font-size:12px">
        Generated by Techno Terminal Test Suite | {datetime.utcnow().isoformat()}
    </p>
</body>
</html>"""
        
        return self._send_email(
            subject=f"[Test Report] {module_name} — {passed}/{total} passed ({pass_rate}%)",
            html_body=html,
        )
    
    def send_summary_report(
        self,
        all_modules: list[dict],
        total_tests: int,
        total_passed: int,
        total_failed: int,
        environment: str = "local",
    ) -> bool:
        """
        Send a final summary report after all modules have run.
        
        Args:
            all_modules: List of dicts with keys: name, total, passed, failed, failures
            total_tests: Grand total
            total_passed: Grand passed count
            total_failed: Grand failed count
            environment: Test environment
        """
        pass_rate = round((total_passed / total_tests * 100) if total_tests > 0 else 0, 1)
        
        module_rows = ""
        for m in all_modules:
            color = "green" if m["failed"] == 0 else "red"
            module_rows += f"""<tr>
                <td style="border:1px solid #ddd;padding:8px">{m['name']}</td>
                <td style="border:1px solid #ddd;padding:8px">{m['total']}</td>
                <td style="border:1px solid #ddd;padding:8px">{m['passed']}</td>
                <td style="border:1px solid #ddd;padding:8px;color:{color}">{m['failed']}</td>
            </tr>"""
        
        html = f"""<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; }}
        .header {{ background: {"#4CAF50" if total_failed == 0 else "#f44336"}; color: white; padding: 20px; border-radius: 5px; }}
    </style>
</head>
<body>
    <div class="header">
        <h2>🏁 Final Test Suite Summary</h2>
        <p>Environment: {environment} | {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC</p>
    </div>
    
    <h3>Overall</h3>
    <p>Total: {total_tests} | Passed: {total_passed} | Failed: {total_failed} | Rate: {pass_rate}%</p>
    
    <h3>Per Module</h3>
    <table style="border-collapse:collapse;width:100%">
        <thead><tr style="background:#2196F3;color:white">
            <th style="border:1px solid #ddd;padding:8px">Module</th>
            <th style="border:1px solid #ddd;padding:8px">Total</th>
            <th style="border:1px solid #ddd;padding:8px">Passed</th>
            <th style="border:1px solid #ddd;padding:8px">Failed</th>
        </tr></thead>
        <tbody>{module_rows}</tbody>
    </table>
    
    <h3>All Failures</h3>
    {self._build_html_table(self._all_failures)}
    
    <hr style="margin-top:30px">
    <p style="color:#666;font-size:12px">
        Generated by Techno Terminal Test Suite | {datetime.utcnow().isoformat()}
    </p>
</body>
</html>"""
        
        return self._send_email(
            subject=f"[Final Report] {total_passed}/{total_tests} passed ({pass_rate}%)",
            html_body=html,
        )
    
    def _send_email(self, subject: str, html_body: str) -> bool:
        """Send HTML email via Gmail SMTP."""
        if not self.sender or not self.app_password:
            print("WARNING: GMAIL_SENDER_ADDRESS or GMAIL_APP_PASSWORD not set. Email not sent.")
            return False
        
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = self.sender
        msg["To"] = self.recipient
        
        part = MIMEText(html_body, "html")
        msg.attach(part)
        
        try:
            with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
                server.login(self.sender, self.app_password)
                server.sendmail(self.sender, [self.recipient], msg.as_string())
            print(f"Email sent: {subject}")
            return True
        except Exception as e:
            print(f"WARNING: Failed to send email: {e}")
            return False
